[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # This helps Netlify build your function correctly

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200